name: TownManager
main: me.sirsavary.townmanager.Main
version: 0.7.2
author: SirSavary
commands:
  town:
    description: Top level town command.
    permission: TownManager.Town
    usage:
      /<command>
permissions:
  TownManager.*:
    description: Gives access to all TownManager commands
    default: true
    children:
      TownManager.Town: true
  TownManager.Town:
    description: Allows you to use /town
    default: true
  TownManager.Wand:
    description: Allows you to use the wand
    default: true
  TownManager.Inspect:
    description: Allows you to use the inspection tool
    default: true